name: "arrs"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  prowlarr:
    image: "11notes/prowlarr:2.0.5"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "prowlarr.etc:/prowlarr/etc"
    tmpfs:
      # required for read-only image
      - "/tmp:uid=1000,gid=1000"
    ports:
      - "3000:9696/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  prowlarr.etc:

networks:
  frontend: